### ISSUE TITLE
app not start

### ISSUE THREAD

**Issue by sokary2004** [albertobsd/keyhunt#112]
![Untitled](https://user-images.githubusercontent.com/55245611/137340309-5b10b0d2-1f61-4c07-9b7d-5ff06ed1a21b.png)

App Not start in bsgs mode . why ?

**Comment by sssergy** [comment]
Good afternoon.
I also faced such a problem. This applies to the version for Windows.
After creating the bloom filter, it just crashes without any messages.
The Linux version works stably.
The only thing is that creating a bloom filter at the last 2-5 percent slows down very much, since only one processor thread remains in operation.
