### ISSUE TITLE
Are the speeds accurate? - How?  Great job.

### ISSUE THREAD

**Issue by graffitilogic** [albertobsd/keyhunt#124]
Great work here!   Are these speed estimates correct? 
The start up guide has an estimate at one mode of ~46 Petakeys/Second per thread.

Unless my math is wrong (it often is) - at 46 PetaKeys/Second per thread you could solve Puzzle 64 in less than 7 minutes on one thread.  Yet, it remains unsolved.  (Though, probably not for much longer).

I'm not trying to be dismissive or sound rude I'm just trying to understand what your breakthrough was here for speed compared to kangaroo, vanitysearch, bitcrack and others.  Crucially, how can a CPU-bound process be faster than a GPU-bound approaches to EC Point resolution?   Even on a RTX3090 with overly aggressive point and thread parameters it seems the reasonable upper limit is something like 1700 MKey/s +/- 100MKey/s depending on bloom filter size and compression settings.  For a lopsided comparison a block erupter sha256 ASIC miner (which only does a simple hash on the last nonce - the workload and not the full point maths) tops out at  around 36GHash/s.   - and that is with 96 purpose-built hash circuits per cube. 

Put another way, if you really have a way to hit 46 Petakeys/Second for sustained periods that would imply you are able to create a subset of this functionality and mine with a single CPU at a rate competitive with some mining pools.   Happy retirement to you!

**Comment by albertobsd** [comment]
Hi, as @sssergy said the speed is only for BSGS method that need a publickey to work at that speed
For address the CPU can reach some 1 or 5 Millions keys/s that depend of you CPU frequency and cores (threads)

Puzzle 64 doesn't have publickey available. So we can't reach that speed with only the address.

The test for puzzle 63 is solved in 5  minutes because we have the publickey video: https://youtu.be/6on-v-Cp8O8

The process for mining and for ECC calculations are totally different we can't reach those speed for mining because we can't do math with the sha256.

All those other programs that you mention have different methods to calculate the speed, the speed with kangaroo is great that it say but is difficult to calculate it because it is probabilistic (birthday paradox) so his speed is about more or less that the square( speed showed )

So i hope this clarify your doubts.

Regards!

**Comment by albertobsd** [comment]
> the speed with kangaroo is great that it say but is difficult to calculate it because it is probabilistic (birthday paradox) **so his speed is about more or less that the square( speed showed )**

Is hard for me to know the real speed for kangaroo but the real speed of it is (showed speed)^2

I want to implement that Algorithm too but right now it is a complete mystery for me
