### ISSUE TITLE
Huge random step?

### ISSUE THREAD

**Issue by nikolayresh** [albertobsd/keyhunt#162]
I think that it would be great if you add support for huge random sprints within the range. If you have a huge range adding +1 is not efficient as first selecting a random sub-range and then adding +1

**Comment by albertobsd** [comment]
that is what the `-R` do

**Comment by nikolayresh** [comment]
Then how to set the length of this random range? Parameter -N?

**Comment by albertobsd** [comment]
The random step have some uniform distribution in the Range tha you give to it. So if you range is from 2^0 to 2^256 those steps are going to big each one, if you want some smalls steps you need to specify a small range. And the -N value is the amoung of consecutive keys that the program will search from the random selected range, Example:

```
albertobsd $ ./keyhunt -m address -f tests/64.txt -b 64 -l compress -M -R -n 0x1000000 -t 2
[+] Version 0.2.211117 SSE Trick or treat ¡Beta!, developed by AlbertoBSD
[+] Mode address
[+] Search compress only
[+] Matrix screen
[+] Random mode
[+] Threads : 2
[+] Opening file tests/64.txt
[+] Setting search for btc adddress
[+] N = 0x1000000
[+] Bit Range 64
[+] -- from : 0x8000000000000000
[+] -- to   : 0x10000000000000000
[+] Allocating memory for 1 elements: 0.00 MB
[+] Bloom filter for 1 elements.
[+] Loading data to the bloomfilter total: 0.00 MB
[+] Bloomfilter completed
[+] Sorting data ... done! 1 values were loaded and sorted
Base key: f40c5cb4961b0601 thread 0
Base key: c49c8bf1328f628b thread 1
[+] Total 28402688 keys in 30 seconds: 946756 keys/s
Base key: 877e6aff1a08b1b6 thread 1
Base key: 802168eb359490df thread 0
^C
```

The first round the thread id 0 will check all the keys from f40c5cb4961b0601 to f40c5cb4971b0601 because the N value is 24 bits

the second thread id 1 will check from c49c8bf1328f628b to c49c8bf1338f628b and so on...

the length of the range can be set with `-r A:B` or with `-b bitnumber` each will check N keys from the random start base to it plus N
