### ISSUE TITLE
Use subtracted keys in bsgs mode, possible?

### ISSUE THREAD

**Issue by MajMcCloud** [albertobsd/keyhunt#167]
Hey, 
I have seen you made a post on twitter about using subtracted keys with bsgs mode.
Was this just for presentation of the speed or is it possible?
Im sure I have read somewhere here that you told, not to use many public keys with bsgs mode...

Thank you for explanation!

**Comment by sezginyildirim91** [comment]
More than one key divides the speed in half, so the speed is divided by the number of keys entered.

**Comment by MajMcCloud** [comment]
Thanks for responding. I have seen that already, so it does "only" has impact on speed, right?

**Comment by sezginyildirim91** [comment]
> Thanks for responding. I have seen that already, so it does "only" has impact on speed, right?

True.

**Comment by MajMcCloud** [comment]
Thanks!

**Comment by albertobsd** [comment]
> Was this just for presentation of the speed or is it possible? 

Yes is possible.

>Im sure I have read somewhere here that you told, not to use many public keys with bsgs mode...
 
You can use many publickeys that you one 1000 or 10 millions that doesn't matter you are only limited by the RAM and you only need to take this in consideration each extra publickey means that you are going to need more extra time to complete one single cycle.

A lot of people get desperate to easily because the speed counter doesn't increment, but this only will be update each that the program complete one cycle of calculations for all the publickeys.

Regards!
