### ISSUE TITLE
XPOINT mode and ECDSA pubkeys

### ISSUE THREAD

**Issue by dolaor** [albertobsd/keyhunt#22]
Hi Alberto,

First of all great job for the tool!

I have several questions for you if you don't mind:

1. Is it possible to put an example in the README.md on how to use the XPOINT mode with choosing a scan across all the keyspace range?
2. I saw that @iceland2k14 is also using the BSGS algo to search for multiple pubkeys together. Is his tool corresponding to what you call XPOINT mode?
3. What is the best option in term of speed with using CPU and RAM: the RMD160 or the XPOINT mode? I think it should be the XPOINT mode if it uses the BSGS algo which is RAM dependant. The RMD160  is more suited for GPU use.
4. Is the XPOINT mode currently only compatible with the X value and not with the compressed/uncompressed ECDSA pubkeys?
5. The most important question: Do you know a script or a database to get the X value or the compressed/uncompressed ECDSA pubkeys from dormant addresses with positive BTC balance? I think it should be a good idea to make such database that can be use with keyhunt :) I have seen the [tool](https://github.com/graymauser/btcposbal2csv) from @graymauser but I don't think it retrieve the ECDSA pubkeys.
6. What do you think about this [tool](https://github.com/tieanminer/Plutus-fastecdsa) as compared to the RMD160 or the XPOINT mode

Thanks!

**Comment by albertobsd** [comment]
> First of all great job for the tool!

Thanks!

> 1. Is it possible to put an example in the README.md on how to use the XPOINT mode with choosing a scan across all the keyspace range?

Yes i have that task in my todo list, i will notify you when that task was done.

The think that i can tell for sure that xpoint or x value method is reallly cool becauase you can make several copies of the same publickey with diferent value and test some 100 millions of diferent copies of the same "Point" and if you hit one of those copies you can recalculate the original privatekey

> 2. I saw that @iceland2k14 is also using the BSGS algo to search for multiple pubkeys together. Is his tool corresponding to what you call XPOINT mode?

I don't think so, his BSGS approach is the same algorimth tha my tool use.

> 3. What is the best option in term of speed with using CPU and RAM: the RMD160 or the XPOINT mode? I think it should be the XPOINT mode if it uses the BSGS algo which is RAM dependant. The RMD160  is more suited for GPU use.

both method use the same approch, this is generate the keys one y one and compare it againts the file list (this is made in RAM with help of the bloom filter).

both use more o less the same amount of RAM. xpoint mode doesn't have anything relate with bsgs, the only similar in both is that those two methods use the information of the publickey.

If you see xpoint and rmd160 in terms of speed i can tell you that xpoint is faster than rmd160 because it use less processor because xpoint evaluate the X value of the publickey and don't do any hash operation. rmd160 mode use both `sha256` and `rmd160` per publickey generated this mean more use of processor and less speed. Also rmd160 do that operations twice, because the `compress` an `uncompress` publickey

> 4. Is the XPOINT mode currently only compatible with the X value and not with the compressed/uncompressed ECDSA pubkeys?

Actually xpoint can use the next 3 values:

- X value of the publickey (64 hexchars)
- Publickey in compress format. (66 hexchars)
- Publickey in uncompress format (130 hexchars)

> 5. The most important question: Do you know a script or a database to get the X value or the compressed/uncompressed ECDSA pubkeys from dormant addresses with positive BTC balance? I think it should be a good idea to make such database that can be use with keyhunt :) I have seen the [tool](https://github.com/graymauser/btcposbal2csv) from @graymauser but I don't think it retrieve the ECDSA pubkeys.

I dont have that script but im pretty sure i been see it in some telegrams groups, but having a list with address is easy make some script that search if that address have publickey leaked in some blockchain API.

> 6. What do you think about this [tool](https://github.com/tieanminer/Plutus-fastecdsa) as compared to the RMD160 or the XPOINT mode

Well the tools like like any other tool, i don't test his speed but usually (not always) python tools are slow than compiled tools, this is because python is a interpeted language, they usually can reach some 90 or 80% of the speed of compiled tools.

Can you tellme what is the speed of that tool?

best regards!

**Comment by dolaor** [comment]
Thanks for the quick reply!

Ok I got it now with the XPOINT method. Indeed It is not related to the BSGS algo. Sorry for the confusion.
Yes the XPOINT method should be faster since there is less hash functions involved in the process.
I did not measure the speed for the last tool but yours should be faster since it is a compiled tool and since XPOINT involved less hash functions :)
Please keep me in the loop via [email](dolaor@outlook.com) if you find a tool or a database to have a list of dormant ECDSA pubkeys with positive BTC balance. In the meantimes I will try to do it myself but I am currently learning how to code so it will take some time ^^ Please Let me know also if you have an idea on how to do such tool.
I have also another quick math question. Why in the BSGS multiple pubkeys tool of @iceland2k14 he is using a range of "1:7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0" instead of "1:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141" which is the max search range for privkeys.

Thanks a lot!
